# Generated by Django 4.0.4 on 2022-05-28 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('birthday', models.CharField(blank=True, max_length=50, null=True)),
                ('contact', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Xodimlar',
            },
        ),
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Parol',
            },
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.CharField(max_length=20, null=True, verbose_name='Zayavkalar soni')),
                ('called', models.CharField(blank=True, max_length=20, null=True, verbose_name='Gaplashildi')),
                ('sells', models.CharField(blank=True, max_length=20, null=True, verbose_name='Sotilgan masulotlar')),
                ('no_called', models.CharField(blank=True, max_length=20, null=True, verbose_name="Teliga tushib bo'lmaganlar soni")),
                ('error_num', models.CharField(blank=True, max_length=20, null=True, verbose_name="Noto'g'ri raqamlar")),
                ('number_x', models.CharField(blank=True, max_length=20, null=True, verbose_name='Otkazlar soni')),
                ('report_x', models.CharField(blank=True, max_length=20, null=True, verbose_name='Buyutma bermagan yoki adashganlar')),
                ('cash_pay', models.CharField(blank=True, max_length=20, null=True, verbose_name="Naqd to'lovlar soni")),
                ('click_pay', models.CharField(blank=True, max_length=20, null=True, verbose_name="Click orqali to'lovlar soni")),
                ('other_pay', models.CharField(blank=True, max_length=20, null=True, verbose_name="Boshqa usuldagi to'lovlar")),
                ('special_pay', models.CharField(blank=True, max_length=20, null=True, verbose_name='Maxsus narxda sotilgan mahsulotlar')),
                ('donation', models.CharField(blank=True, max_length=20, null=True, verbose_name='Ehsonlar soni')),
                ('num_customer', models.CharField(blank=True, max_length=20, null=True, verbose_name='Sotib olgan mijozlar soni')),
                ('money', models.CharField(max_length=20, null=True, verbose_name='Summa')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tg.employees')),
            ],
            options={
                'verbose_name': 'Hisobotlar',
            },
        ),
    ]
